### ISSUE TITLE
An error occures after few moments of running the launch file.

### ISSUE THREAD

**Issue by s-a-tanjim** [Fivecomm/fivecomm_5g_router#1]
Don't know why I'm getting the error... :/
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tanjim/Downloads/test/ws/src/fivecomm_5g_router/scripts/modemInfo.py", line 62, in getDataFromModem
    if not s.login(modem_gateway, modem_username, modem_password):
  File "/usr/lib/python3/dist-packages/pexpect/pxssh.py", line 432, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
```

**Comment by PabloTrelisFivecomm** [comment]
The package currently works exclusively for the Fivecomm 5G-BROAD, I attach the product link. (https://fivecomm.eu/fivecomm-5g-devices/)

The error is due to the fact that it is trying to establish an ssh connection with the router and cannot find it.
